### ISSUE TITLE
Standardize error handling with Toast notifications

### ISSUE THREAD

**Issue by dwrx** [proxycapital/solana-civ-frontend#40]
Currently, frontend has copy/paste error handling implemented within try/catch blocks in various components. We need to standardize error handling and toast notifications:

1) Update the try/catch blocks in all components to follow a standardized error handling approach:
- Modify the toast.promise call to set the error message to undefined.
- Implement a custom error handling logic within the catch block that:
-- Checks for specific error codes.
-- Displays a user-friendly message corresponding to the error code.
-- Falls back to a generic error message if the error code is not recognized.

All possible error codes are available in Rust repo: 
https://github.com/proxycapital/solana-civ/blob/main/programs/solciv/src/errors.rs

Generic error messages should still be in the context of the failed action, so not "Some error...", but "Failed to move unit", "Failed to build a city" etc in the context of the failed request. Keep the generic errors in the same utility file as other documented errors from `errors.rs`, for example, `"genericMoveUnitError": "Failed to move unit"` for potential re-usage across multiple components and/or future localisation.

```
// Before:
try {
  // ........
} catch (error) {
  console.log("Error upgrading land tile: ", error);
  if (error instanceof Error && error.message.includes("TileNotControlled")) {
    toast.error("Tile is not controlled", { autoClose: 3000 });
    // ......
  }
}
```
```
// After:
import { handleError } from 'errorCodes.ts';

try {
  // .......
} catch (error) {
  handleError(error, "production-queue");
  console.log("Error upgrading land tile: ", error);
}
```
 
2) Prepare the ground for future localization by integrating i18n support for toast notifications.

**Comment by yaywhatnut** [comment]
To fix the problem and implement standardized error handling and toast notifications, follow these steps:

1. **Modify the toast.promise call:**
   Update the toast.promise call to set the error message to undefined. This ensures that the toast notification displays the correct error message.

2. **Implement custom error handling logic:**
   Within the catch block, implement custom error handling logic that checks for specific error codes. You can use the error codes available in the Rust repository provided:

   - Check for specific error codes.
   - Display user-friendly messages corresponding to the error codes.
   - Provide fallback to a generic error message if the error code is not recognized.

3. **Organize generic error messages:**
   Ensure that generic error messages are still in the context of the failed action. For example, use "Failed to move unit" or "Failed to build a city" instead of generic messages like "Some error...".

   Keep the generic errors in the same utility file as other documented errors from errors.rs for potential re-usage across multiple components and future localization.

Here's how you can implement these changes in your code:

```javascript
import { handleError } from 'errorCodes.ts'; // Import your error handling utility

try {
  // Your code logic here
} catch (error) {
  // Call the custom error handling function with the error and the relevant context
  handleError(error, "production-queue"); // Replace "production-queue" with your specific context
  console.log("Error upgrading land tile: ", error);
}
```

In the `handleError` function:

- Check the error object for specific error codes.
- Display user-friendly messages corresponding to the error codes.
- Use generic error messages in the context of the failed action.
- Ensure that the function handles error messages gracefully and provides clear feedback to the user.

By following these steps, you can standardize error handling and toast notifications in your frontend components, ensuring consistency and better user experience.                                                                                                                                                                     Here are some YouTubers who specialize in frontend development and might provide helpful tutorials and guides on error handling, toast notifications, and best practices:

1. Traversy Media: Brad Traversy covers a wide range of frontend development topics and often provides practical tutorials on JavaScript, React, and error handling techniques.

2. Academind: Maximilian Schwarzmüller's channel offers comprehensive tutorials on frontend development, including React, Angular, and Vue.js. He often dives into advanced topics and best practices, which could include error handling strategies.

3. The Net Ninja: Shaun Pelling, known as The Net Ninja, creates beginner-friendly tutorials on various frontend technologies such as JavaScript, React, and Vue.js. He might have videos specifically addressing error handling and toast notifications.

4. Fireship: Jeff Delaney's channel focuses on web development tips, tricks, and tutorials. He covers a wide range of topics including JavaScript, Firebase, and Angular, which might include videos on error handling best practices.

5. LevelUpTuts* Scott Tolinski's channel offers tutorials on frontend technologies, including JavaScript frameworks like React and Vue.js. He might have videos discussing error handling patterns and best practices.

These YouTubers regularly update their channels with new content, so you might find videos that directly address your frontend development challenges, including error handling and toast notifications. Be sure to explore their channels and playlists to find relevant tutorials and guides.
